//
// Created by diogenes on 20/06/17.
//

#ifndef DISK_DRIVE_DEFAULT_PARAMS_HPP
#define DISK_DRIVE_DEFAULT_PARAMS_HPP


#define TRACKS_PER_CILINDER 5
#define SECTORS_PER_TRACK 60
#define TRACKS_PER_SURFACE 10
#define SIZE_SECTOR_IN_BYTES 512
#define SIZE_CLUSTER 4
#define TIME_SEEK_AVR 4
#define TIME_SEEK_MIN 1
#define TIME_LATENCY_AVR 6
#define TIME_TRANSFER 12

#define MAX_SECTORS (TRACKS_PER_CILINDER * TRACKS_PER_SURFACE * SECTORS_PER_TRACK)
#define MAX_FILES 10


#endif //DISK_DRIVE_DEFAULT_PARAMS_HPP
